[build]
  command = "npm i"
  functions = "src/functions"

[template.environment]
  WEBFLOW_TOKEN= "Add the WEBFLOW_TOKEN credential here"
  FOXY_WEBFLOW_COLLECTION= "Add the FOXY_WEBFLOW_COLLECTION credential here"
  FOXY_API_CLIENT_ID= "Add the FOXY_API_CLIENT_ID credential here"
  FOXY_API_CLIENT_SECRET= "Add the FOXY_API_CLIENT_SECRET credential here"
  FOXY_API_REFRESH_TOKEN= "Add the FOXY_API_REFRESH_TOKEN credential here"
  FOXY_WEBHOOK_ENCRYPTION_KEY= "We will add this one later"