[build]
  command = "npm i"
  functions = "src/functions"

[template.environment]
  WEBFLOW_TOKEN= "Add the WEBFLOW_TOKEN credential here"
  FOXY_WEBFLOW_COLLECTION= "Add the FOXY_WEBFLOW_COLLECTION credential here"